name: Deploy to ECR

on:
  push:

jobs:
  
  build:
    
    name: Build Image
    runs-on: self-hosted

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tech-challenge/lgc
        
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    
    name: Deploy Image
    needs: [build]
    runs-on: self-hosted

    steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Update deployment (using latest chart of actions-runner-controller-charts/auto-scaling-runner-set)
            run: |
              helm upgrade lgc --install --namespace lgc ./helm --wait --set image.repository=${{secrets.ECR_REPOSITORY}}

  
